# Generated by Django 3.2.5 on 2021-07-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('abstract', models.CharField(max_length=1500)),
                ('content', models.CharField(blank=True, max_length=15000)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('page_url', models.CharField(max_length=500)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
