# Generated by Django 3.2.5 on 2021-07-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(blank=True, max_length=25000),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='news',
            name='page_url',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
